### ISSUE TITLE
No preview images

### ISSUE THREAD

**Issue by tobiasdalhof** [sketchmouse/wp-gif-player#9]
The preview images are not being created.

PHP error.log:
`\nWarning: Unable to open '/var/www/netzkonditor/web/wp//app/uploads/2016/11/dom-ready-trigger-1_still_tmp.jpeg' for writing in /var/www/netzkonditor/web/app/plugins/wp-gif-player/gif-player.php on line 264`

Steps I already went thru:
* php.ini `upload_max_filesize = 100M`
* Folder permission of upload folder set to `777`

What else can I do? Running on nginx and hhvm with the latest WP version and https://github.com/roots/bedrock.

**Comment by sketchmouse** [comment]
Hi Tobias,

Thanks for using the WP GIF Player!

I wasn't able to replicate your error, however have a couple of ideas which you could try:

1. The 777 permission you set on the uploaded folder, was this the plugin folder or the uploads (uploads/2016/11/)? As I would try to set 777 on **/uploads/** and **/11/** individually and see if this helped.

2. Otherwise, have you set the **client_max_body_size 100m**; in **nginx.conf**?

Here's a link to the possible fix: 
https://wordimpress.com/wordpress-nginx-http-error-on-image-uploader-fix/

Let me know how you get along!

**Comment by tobiasdalhof** [comment]
Thanks for your replay @sketchmouse 

`nginx.conf` was already configured to `client_max_body_size 100m` and folder permission was set to `777` recursively on `uploads` folder.

wp-gif-player is trying to create the preview file under `https://netzkonditor.de/app/uploads//var/www/netzkonditor/web/wp//app/uploads/2016/11/scrolltiefe-tag-erstellen-1_still_tmp.jpeg`
it is supposed to be ``https://netzkonditor.de/app/uploads/2016/11/scrolltiefe-tag-erstellen-1_still_tmp.jpeg``

Thanks!

**Comment by tobiasdalhof** [comment]
Fixed it! Feel free to have a look at my commits: https://github.com/tobiasdalhof/wp-gif-player/commits/master

**Comment by sketchmouse** [comment]
That's great to hear and thanks for sharing!
